### ISSUE TITLE
similar to graph attention network ?

### ISSUE THREAD

**Issue by ICDI0906** [liulu112601/Gated-Propagation-Net#2]
Hello, great paper! I have a question about propagation from neighbours, is it similar to Graph attention network? 
looking forwork to your reply~

**Comment by liulu112601** [comment]
> Hello, great paper! I have a question about propagation from neighbours, is it similar to Graph attention network?
> looking forwork to your reply~

Hi, Thanks for your question.

From the perspective of motivation and task, our propagation idea is inspired by belief propagation, message passing and label propagation. The graph in our paper is a _computational graph_ in which every node is associated with a prototype produced by a CNN rather than a non-parameterized initialization in GNN/GAT. Our goal is to obtain a better prototype representation for classes in few-shot classification while they focus on the node embeddings of the graph-structured data.

From the perspective of implementation, the structure of our model is similar to GAT, with differences that GAT has a linear transformation layer while ours only focus on propagation (from neighbors).

Regards,

**Comment by ICDI0906** [comment]
Thanks for reply Timely, I have another question, why prototype produced by a CNN is superior to non-parameterized initialization?  can you recommend me some paper about this?

**Comment by liulu112601** [comment]
> Thanks for reply Timely, I have another question, why prototype produced by a CNN is superior to non-parameterized initialization? can you recommend me some paper about this?

Hi, Thanks for the follow up.

"prototype produced by a CNN" and "non-parameterized initialization" are for different tasks. (so there is no who is better :) )

I am not an expert in learning over graph-structured data. As far as I know, usually, the model, e.g., GAT, for datasets with graph-structured data, aims to learn better node embeddings by considering the structure, using the node features and the edges defined on the graph (both are given in the datasets). 

CNN is a feature extractor initially designed for images. In the literature of few-shot learning, feature average extracted by CNN has been proved to be effective for the image classification task (see papers below).

Suggestive papers:
- Prototypical Networks for Few-shot Learning ("prototype produced by a CNN" )
- A Comprehensive Survey on Graph Neural Networks (graph-structured data)

Regards,

**Comment by ICDI0906** [comment]
Thanks for your detail explanation, I will read the above paper~
